import{a as h,S as b,i as v}from"./assets/vendor-ChjgTQlz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const L="49186769-dabefba962826c776b77806d1",q="https://pixabay.com/api/";let S=15,d=1;async function p(t){try{const r=await h.get(q,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:d}});return d+=1,r.data.hits}catch(r){return console.error("Error fetching images:",r.message),[]}}function E(){d=1}const P=new b(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function k(t){return t.map(({webformatURL:r,largeImageURL:o,tags:i,likes:e,views:s,comments:l,downloads:g})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${r}" alt="${i}" loading="lazy" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="tittle">Likes</h2><p class="amount">${e}</p></div>
          <div class="block"><h2 class="tittle">Views</h2><p class="amount">${s}</p></div>
          <div class="block"><h2 class="tittle">Comments</h2><p class="amount">${l}</p></div>
          <div class="block"><h2 class="tittle">Downloads</h2><p class="amount">${g}</p></div>
        </div>
      </li>`).join("")}function m(t){document.querySelector(".gallery").insertAdjacentHTML("beforeend",k(t)),P.refresh()}function n(t){v.error({title:"Error",message:t,position:"topRight"})}const y=document.querySelector(".form"),f=document.querySelector(".input-search"),$=document.querySelector(".gallery"),c=document.querySelector(".loader"),u=document.querySelector(".loader-load"),a=document.querySelector(".btn-load");c.style.display="none";a.style.display="none";u.style.display="none";y.addEventListener("submit",function(t){t.preventDefault();const r=f.value.trim();if(r===""){n("Please enter a search query!");return}E(),$.innerHTML="",a.style.display="none",c.style.display="block",p(r).then(o=>{if(c.style.display="none",o.length===0){n("Sorry, there are no images matching your search query. Please try again!");return}m(o),a.style.display="block"}).catch(o=>{c.style.display="none",n("Error fetching images. Please try again!"),console.error("Помилка сервера:",o.message)}),y.reset()});a.addEventListener("click",()=>{u.style.display="block",a.style.display="none",p(f.value.trim()).then(t=>{setTimeout(()=>{if(u.style.display="none",t.length===0){a.style.display="none",n("We're sorry, but you've reached the end of search results.");return}m(t),a.style.display="block"},100)}).catch(t=>{u.style.display="none",n("Error loading more images."),console.error("Помилка сервера:",t.message)})});
//# sourceMappingURL=index.js.map
