import{a as v,S,i as q}from"./assets/vendor-ChjgTQlz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const L="49186769-dabefba962826c776b77806d1",E="https://pixabay.com/api/";let P=15,u=1;async function p(e){try{const r=await v.get(E,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:u}});return u+=1,r.data.hits}catch(r){return console.error("Error fetching images:",r.message),[]}}function k(){u=1}const w=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function $(e){return e.map(({webformatURL:r,largeImageURL:s,tags:i,likes:t,views:o,comments:a,downloads:b})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${r}" alt="${i}" loading="lazy" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="tittle">Likes</h2><p class="amount">${t}</p></div>
          <div class="block"><h2 class="tittle">Views</h2><p class="amount">${o}</p></div>
          <div class="block"><h2 class="tittle">Comments</h2><p class="amount">${a}</p></div>
          <div class="block"><h2 class="tittle">Downloads</h2><p class="amount">${b}</p></div>
        </div>
      </li>`).join("")}function m(e){document.querySelector(".gallery").insertAdjacentHTML("beforeend",$(e)),w.refresh(),g()}function n(e){q.error({title:"Error",message:e,position:"topRight"})}function g(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,left:0,behavior:"smooth"})}}const y=document.querySelector(".form"),h=document.querySelector(".input-search"),M=document.querySelector(".gallery"),c=document.querySelector(".loader"),d=document.querySelector(".loader-load"),f=document.querySelector(".loader-end"),l=document.querySelector(".btn-load");c.style.display="none";l.style.display="none";d.style.display="none";f.style.display="none";y.addEventListener("submit",function(e){e.preventDefault();const r=h.value.trim();if(r===""){n("Please enter a search query!");return}k(),M.innerHTML="",l.style.display="none",c.style.display="block",p(r).then(s=>{if(c.style.display="none",s.length===0){n("Sorry, there are no images matching your search query. Please try again!"),f.style.display="block";return}m(s),l.style.display="block"}).catch(s=>{c.style.display="none",n("Error fetching images. Please try again!"),console.error("Помилка сервера:",s.message)}),y.reset()});l.addEventListener("click",async()=>{d.style.display="block",l.style.display="none",await p(h.value.trim()).then(e=>{if(d.style.display="none",e.length===0){l.style.display="none",n("We're sorry, but you've reached the end of search results.");return}m(e),g(),l.style.display="block"}).catch(e=>{d.style.display="none",n("Error loading more images."),console.error("Помилка сервера:",e.message)})});
//# sourceMappingURL=index.js.map
